### ISSUE TITLE
Can't edit body with Vim

### ISSUE THREAD

**Issue by graypegg** [shahin8r/http-gui#1]
Trying to edit the body with Vim set as my default editor doesn't seem to work. [Example.](https://asciinema.org/a/85roxdyhhtuj5eagqdzbklu7l)
I think this is an issue with Blessed's `.readEditor()` method, but I thought I'd post an issue here too.

**Comment by shahin8r** [comment]
Yep, you're absolutely right. Running the [`widget-textarea`](https://github.com/chjj/blessed/blob/master/test/widget-textarea.js) test from the Blessed repo fails as well. Thanks for the heads up.

**Comment by derhuerst** [comment]
I guess you could either use `.readEditor` or try using [`editor-widget`](https://github.com/slap-editor/editor-widget#editor-widget-), which [I have used before](https://github.com/derhuerst/js-playgrounds/blob/e515e0b/js-playgrounds).

**Comment by shahin8r** [comment]
Hey guys. I can't reproduce this problem anymore, not sure why either. Are you experiencing the same?

**Comment by derhuerst** [comment]
@toish If you're still having problems, please check one of [my projects, `sms-cli`](https://github.com/derhuerst/sms-cli) using Vim, because it spawns an editor as well, but doesn't use blessed.
